# Generated by Django 4.0.5 on 2022-07-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_city_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='last_update',
        ),
        migrations.AddField(
            model_name='city',
            name='country_code',
            field=models.CharField(default='UK', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='openweather_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
