# Generated by Django 4.0.5 on 2022-07-09 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_alter_city_openweather_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(default=0)),
                ('feels_like', models.FloatField(default=0)),
                ('pressure', models.IntegerField(default=0)),
                ('wind_speed', models.FloatField(default=0)),
                ('description', models.CharField(max_length=50)),
                ('desc_short', models.CharField(max_length=30, verbose_name='short description')),
                ('icon_name', models.CharField(max_length=10)),
                ('last_update', models.DateTimeField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city')),
            ],
        ),
    ]
