# Generated by Django 4.0.5 on 2022-07-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_alter_city_name_currentweather'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweather',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
    ]
