# Generated by Django 4.0.5 on 2022-10-23 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_currentweather_humidity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentweather',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weather.city'),
        ),
        migrations.CreateModel(
            name='CityStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.city')),
            ],
        ),
    ]
