# Generated by Django 4.0.5 on 2022-10-23 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_alter_currentweather_city_citystats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentweather',
            name='id',
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='weather.city'),
        ),
    ]
