# Generated by Django 4.0.5 on 2022-10-24 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0012_alter_currentweather_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentweather',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='weather', serialize=False, to='weather.city'),
        ),
    ]
