# Generated by Django 4.0.5 on 2022-10-24 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0013_alter_currentweather_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citystats',
            options={'verbose_name_plural': 'Статистика по городам'},
        ),
    ]
