# Generated by Django 4.0.5 on 2022-10-24 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0014_alter_citystats_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citystats',
            name='id',
        ),
        migrations.AlterField(
            model_name='citystats',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='weather.city'),
        ),
    ]
