# Generated by Django 4.0.5 on 2022-10-24 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0015_remove_citystats_id_alter_citystats_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citystats',
            name='city',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='weather.city'),
        ),
    ]
