# Generated by Django 4.0.5 on 2022-10-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0016_alter_citystats_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
