# Generated by Django 4.0.5 on 2022-10-24 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0017_city_latitude_city_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Дашборд',
                'verbose_name_plural': 'Дашборд',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('weather.citystats',),
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Города'},
        ),
        migrations.AlterModelOptions(
            name='citystats',
            options={'verbose_name': 'Статистика по городам', 'verbose_name_plural': 'Статистика по городам'},
        ),
        migrations.AlterModelOptions(
            name='currentweather',
            options={'verbose_name': 'Прогноз', 'verbose_name_plural': 'Прогнозы'},
        ),
    ]
