# Generated by Django 4.0.5 on 2022-10-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0018_statssummary_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='russian_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
