# Generated by Django 4.0.5 on 2022-10-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0019_city_russian_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweather',
            name='russian_desc',
            field=models.CharField(default='_', max_length=50),
        ),
        migrations.AlterField(
            model_name='city',
            name='russian_name',
            field=models.CharField(default='_', max_length=50),
        ),
    ]
