# Generated by Django 4.0.5 on 2022-10-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0020_currentweather_russian_desc_alter_city_russian_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentweather',
            name='russian_desc',
            field=models.CharField(default='_', max_length=50, verbose_name='russian description'),
        ),
    ]
